# Setup
title: JiaWang Zhang's Blog
description: >- # this means to ignore newlines until "baseurl:"
  A Horizontal development Software Testing Engineer.
  Explore the infinite possibility.
url: "https://blog.noel-zhang.work" 
avatar: /avatar.jpeg
paginate: 5
permalink: /:year/:month/:day/:title
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
logo: logo.png
social:
  name: Songzi Vong
  links:
    - https://github.com/jiaw-Zh
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: JiaWang Zhang
  url: https://github.com/jiaw-Zh
  email: zjw5734@gmail.com
